# Server Configuration
server:
  port: 3002

spring:
  application:
    name: complaint-service
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123

  # Database Configuration

  datasource:
    url: jdbc:postgresql://localhost:5432/microservices_db
    username: admin
    password: admin123
    hikari:
      connection-timeout: 60000
      initialization-fail-timeout: -1


  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  # Flyway Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    connect-retries: 10
    connect-retries-interval: 2
    clean-disabled: false

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    com.projeto.complaintservice: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'

