global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.0.169:8090']

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.0.169:3001']

  - job_name: 'complaint-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.0.169:3002']

  - job_name: 'protocol-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.0.169:3003']

  - job_name: 'admin-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.0.169:3004']

  - job_name: 'report-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.0.169:3005']

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.0.169:3006']
